// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wechat} from '../models';
import {main} from '../models';
import {wxapkg} from '../models';
import {decomp} from '../models';
import {scanner} from '../models';

export function ClipboardWrite(arg1:string):Promise<void>;

export function DecompileDir(arg1:string):Promise<string>;

export function DeletePackageCache(arg1:string,arg2:string):Promise<wechat.CacheDir>;

export function DeletePackageCaches(arg1:string,arg2:Array<string>):Promise<wechat.CacheCleanup>;

export function DetectWeChatRoots():Promise<Array<wechat.RootInfo>>;

export function ExportReport(arg1:string,arg2:string):Promise<string>;

export function GetTask(arg1:string):Promise<main.Task>;

export function InspectPackage(arg1:string,arg2:string):Promise<Array<wxapkg.Entry>>;

export function LastDecompile():Promise<decomp.Result>;

export function LastScanResult():Promise<scanner.Result>;

export function LegalNotice():Promise<string>;

export function ListDir(arg1:string):Promise<Array<main.DirEntry>>;

export function ListTasks():Promise<Array<main.Task>>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function PackageCacheInfo(arg1:string,arg2:string):Promise<wechat.CacheDir>;

export function PickDirectory(arg1:string):Promise<string>;

export function PickWxapkgFiles():Promise<Array<string>>;

export function ReadSource(arg1:string,arg2:string):Promise<main.SourceView>;

export function ScanDir(arg1:string):Promise<string>;

export function ScanPackages(arg1:string):Promise<Array<wechat.PackageRef>>;

export function Unpack(arg1:main.UnpackRequest):Promise<string>;

export function VersionInfo():Promise<string>;
