// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClipboardWrite(arg1) {
  return window['go']['main']['App']['ClipboardWrite'](arg1);
}

export function DecompileDir(arg1) {
  return window['go']['main']['App']['DecompileDir'](arg1);
}

export function DeletePackageCache(arg1, arg2) {
  return window['go']['main']['App']['DeletePackageCache'](arg1, arg2);
}

export function DeletePackageCaches(arg1, arg2) {
  return window['go']['main']['App']['DeletePackageCaches'](arg1, arg2);
}

export function DetectWeChatRoots() {
  return window['go']['main']['App']['DetectWeChatRoots']();
}

export function ExportReport(arg1, arg2) {
  return window['go']['main']['App']['ExportReport'](arg1, arg2);
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function InspectPackage(arg1, arg2) {
  return window['go']['main']['App']['InspectPackage'](arg1, arg2);
}

export function LastDecompile() {
  return window['go']['main']['App']['LastDecompile']();
}

export function LastScanResult() {
  return window['go']['main']['App']['LastScanResult']();
}

export function LegalNotice() {
  return window['go']['main']['App']['LegalNotice']();
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function PackageCacheInfo(arg1, arg2) {
  return window['go']['main']['App']['PackageCacheInfo'](arg1, arg2);
}

export function PickDirectory(arg1) {
  return window['go']['main']['App']['PickDirectory'](arg1);
}

export function PickWxapkgFiles() {
  return window['go']['main']['App']['PickWxapkgFiles']();
}

export function ReadSource(arg1, arg2) {
  return window['go']['main']['App']['ReadSource'](arg1, arg2);
}

export function ScanDir(arg1) {
  return window['go']['main']['App']['ScanDir'](arg1);
}

export function ScanPackages(arg1) {
  return window['go']['main']['App']['ScanPackages'](arg1);
}

export function Unpack(arg1) {
  return window['go']['main']['App']['Unpack'](arg1);
}

export function VersionInfo() {
  return window['go']['main']['App']['VersionInfo']();
}
