// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeCapture() {
  return window['go']['main']['App']['AnalyzeCapture']();
}

export function CAInfo() {
  return window['go']['main']['App']['CAInfo']();
}

export function CaptureStatus() {
  return window['go']['main']['App']['CaptureStatus']();
}

export function ClearFlows() {
  return window['go']['main']['App']['ClearFlows']();
}

export function ClipboardWrite(arg1) {
  return window['go']['main']['App']['ClipboardWrite'](arg1);
}

export function CloseCapture() {
  return window['go']['main']['App']['CloseCapture']();
}

export function DecompileDir(arg1) {
  return window['go']['main']['App']['DecompileDir'](arg1);
}

export function DeletePackageCache(arg1, arg2) {
  return window['go']['main']['App']['DeletePackageCache'](arg1, arg2);
}

export function DeletePackageCaches(arg1, arg2) {
  return window['go']['main']['App']['DeletePackageCaches'](arg1, arg2);
}

export function DetectWeChatRoots() {
  return window['go']['main']['App']['DetectWeChatRoots']();
}

export function ExportCA(arg1) {
  return window['go']['main']['App']['ExportCA'](arg1);
}

export function ExportCaptureExcel(arg1) {
  return window['go']['main']['App']['ExportCaptureExcel'](arg1);
}

export function ExportReport(arg1, arg2) {
  return window['go']['main']['App']['ExportReport'](arg1, arg2);
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function InspectPackage(arg1, arg2) {
  return window['go']['main']['App']['InspectPackage'](arg1, arg2);
}

export function InstallCA() {
  return window['go']['main']['App']['InstallCA']();
}

export function LastCrossReport() {
  return window['go']['main']['App']['LastCrossReport']();
}

export function LastDecompile() {
  return window['go']['main']['App']['LastDecompile']();
}

export function LastScanResult() {
  return window['go']['main']['App']['LastScanResult']();
}

export function LegalNotice() {
  return window['go']['main']['App']['LegalNotice']();
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function ListFlows(arg1) {
  return window['go']['main']['App']['ListFlows'](arg1);
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function PackageCacheInfo(arg1, arg2) {
  return window['go']['main']['App']['PackageCacheInfo'](arg1, arg2);
}

export function PickDirectory(arg1) {
  return window['go']['main']['App']['PickDirectory'](arg1);
}

export function PickWxapkgFiles() {
  return window['go']['main']['App']['PickWxapkgFiles']();
}

export function ReadSource(arg1, arg2) {
  return window['go']['main']['App']['ReadSource'](arg1, arg2);
}

export function ScanDir(arg1) {
  return window['go']['main']['App']['ScanDir'](arg1);
}

export function ScanPackages(arg1) {
  return window['go']['main']['App']['ScanPackages'](arg1);
}

export function StartCapture(arg1) {
  return window['go']['main']['App']['StartCapture'](arg1);
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}

export function SysProxyEnable() {
  return window['go']['main']['App']['SysProxyEnable']();
}

export function SysProxyRestore() {
  return window['go']['main']['App']['SysProxyRestore']();
}

export function SysProxyState() {
  return window['go']['main']['App']['SysProxyState']();
}

export function UninstallCA() {
  return window['go']['main']['App']['UninstallCA']();
}

export function Unpack(arg1) {
  return window['go']['main']['App']['Unpack'](arg1);
}

export function VersionInfo() {
  return window['go']['main']['App']['VersionInfo']();
}
