// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cross} from '../models';
import {main} from '../models';
import {wechat} from '../models';
import {wxapkg} from '../models';
import {decomp} from '../models';
import {scanner} from '../models';
import {proxy} from '../models';

export function AnalyzeCapture():Promise<cross.Report>;

export function CAInfo():Promise<main.CAInfo>;

export function CaptureStatus():Promise<main.CaptureStatus>;

export function ClearFlows():Promise<void>;

export function ClipboardWrite(arg1:string):Promise<void>;

export function CloseCapture():Promise<void>;

export function DecompileDir(arg1:string):Promise<string>;

export function DeletePackageCache(arg1:string,arg2:string):Promise<wechat.CacheDir>;

export function DeletePackageCaches(arg1:string,arg2:Array<string>):Promise<wechat.CacheCleanup>;

export function DetectWeChatRoots():Promise<Array<wechat.RootInfo>>;

export function ExportCA(arg1:string):Promise<string>;

export function ExportCaptureExcel(arg1:string):Promise<string>;

export function ExportReport(arg1:string,arg2:string):Promise<string>;

export function GetTask(arg1:string):Promise<main.Task>;

export function InspectPackage(arg1:string,arg2:string):Promise<Array<wxapkg.Entry>>;

export function InstallCA():Promise<main.CAInfo>;

export function LastCrossReport():Promise<cross.Report>;

export function LastDecompile():Promise<decomp.Result>;

export function LastScanResult():Promise<scanner.Result>;

export function LegalNotice():Promise<string>;

export function ListDir(arg1:string):Promise<Array<main.DirEntry>>;

export function ListFlows(arg1:number):Promise<Array<proxy.Flow>>;

export function ListTasks():Promise<Array<main.Task>>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function PackageCacheInfo(arg1:string,arg2:string):Promise<wechat.CacheDir>;

export function PickDirectory(arg1:string):Promise<string>;

export function PickWxapkgFiles():Promise<Array<string>>;

export function ReadSource(arg1:string,arg2:string):Promise<main.SourceView>;

export function ScanDir(arg1:string):Promise<string>;

export function ScanPackages(arg1:string):Promise<Array<wechat.PackageRef>>;

export function StartCapture(arg1:main.CaptureOptions):Promise<main.CaptureStatus>;

export function StopCapture():Promise<main.CaptureStatus>;

export function SysProxyEnable():Promise<proxy.SysProxyState>;

export function SysProxyRestore():Promise<proxy.SysProxyState>;

export function SysProxyState():Promise<proxy.SysProxyState>;

export function UninstallCA():Promise<main.CAInfo>;

export function Unpack(arg1:main.UnpackRequest):Promise<string>;

export function VersionInfo():Promise<string>;
